#解决中文乱码
server:
  servlet:
    encoding:
      enabled: true
      force: true
      charset: utf-8

#单引号控制台会将 \n 作为字符串输出，双引号作为换行字符
#换句话说单引号会转义，双引号不会转义
#yaml 中 -x 代表 X（大写）
person:
  user-name: 张三
  boss: true
  birth: 1997/1/1
  age: 24
  interests:
    - 篮球
    - 电子游戏
  animal: [猫, 狗]
  score: {english: 80, math: 90}
  salarys:
    - 12000
    - 12400.2
  pet:
    name: 船长
    weight: 20.4
  allPets:
    sick:
      - {name: 低音炮, weight: 30}
      - name: 腾龙
        weight: 23.4
    health:
      - { name: 阿明, weight: 33 }
      - { name: 月光, weight: 12 }